import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { headers } from "next/headers";
import "./globals.css";
import SessionProvider from "@/components/auth/SessionProvider";
import UserMenu from "@/components/auth/UserMenu";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Find My Website - Domain Recovery Platform",
  description: "Analyze domains, view Wayback Machine history, and generate recovery scripts",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Read the nonce generated by middleware for CSP
  const headersList = await headers();
  const nonce = headersList.get("x-nonce") ?? "";

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        nonce={nonce}
      >
        <SessionProvider>
          {/* Header with Navigation */}
          <header className="border-b border-gray-200 bg-white sticky top-0 z-50">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="flex justify-between items-center h-16">
                {/* Logo */}
                <Link href="/" className="flex items-center gap-2">
                  <span className="text-2xl">🔍</span>
                  <span className="text-xl font-bold text-gray-900">Find My Website</span>
                </Link>

                {/* User Menu */}
                <UserMenu />
              </div>
            </div>
          </header>

          {/* Main Content */}
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
